### ISSUE TITLE
Well done!

### ISSUE THREAD

**Issue by lopo12123** [evanw/polywasm#1]
Well done!

Although this project may still be in its infancy, I hope you can use some build tools (such as rollup) to build npm packages.

I found that there are a lot of `var` in the code after pulling down and lost ts disclaimer, this is not very friendly for project-level usage.

**Comment by evanw** [comment]
I'm not quite sure what you're saying, sorry. There is already a npm package: https://www.npmjs.com/package/polywasm. And the presence of the `var` keyword is completely irrelevant to how you use this library. I'm closing this issue because it doesn't seem like anything needs to be done here.
