### ISSUE TITLE
edge case access to detached `ArrayBuffer`

### ISSUE THREAD

**Issue by ghost** [evanw/polywasm#3]
This library will sometimes generate code that looks something like this:

~~~ JavaScript
c.dv.getInt32((t2 = (f[256]())), 1)
~~~

If the function `f[256]` happens to grow the memory, this code will be incorrect, because `c.dv` has already been evaluated, and will refer to the previous `DataView`, whose `ArrayBuffer` has already been (explicitly) detached in `f[256]`.

For that particular case, a correctly‐generated code might look something like this:

~~~ JavaScript
(t2 = f[256](), c.dv.getInt32(t2, 1))
~~~

This way, `c.dv` will only be evaluated after `f[256]` returns.

**Comment by evanw** [comment]
Thanks for the report. I can reproduce the issue. I guess this means that [this concern](https://github.com/evanw/polywasm/blob/402a3de74fecdaf29b39024d9f4cfaf843727cb4/src/compile.ts#L804-L806) can be hit in practice. I'll think about what to do here.

**Comment by evanw** [comment]
I was able to fix this by preventing the inlining of all child expressions into `load` and `store` and `memory_copy` and `memory_fill` opcodes. I avoided the performance hit by making an exception for `const` and `local_get` opcodes, which can't contain a `memory_grow` opcode.
